<?php

class JustifiedgalleryFormat extends FormatAbstract
{
    const MIME_TYPE = 'text/html';

    public function stringify()
    {
        $queryString = $_SERVER['QUERY_STRING'];

        $extraInfos = $this->getExtraInfos();
        $formatFactory = new FormatFactory();
        $buttons = [];
        $linkTags = [];
        foreach ($formatFactory->getFormatNames() as $format) {
            // Dynamically build buttons for all formats (except Justifiedgallery)
            if ($format === 'Justifiedgallery') {
                continue;
            }

            // Parse the query string into an associative array
            parse_str($queryString, $queryParams);

            // Update the 'format' parameter and remove 'groupImages'
            $queryParams['format'] = $format;
            unset($queryParams['groupImages']);

            // Rebuild the query string with modifications
            $queryString = http_build_query($queryParams);

            // Create the format URL
            $formatUrl = '?' . $queryString;

            $buttons[] = [
                'href' => $formatUrl,
                'value' => $format,
            ];
            $linkTags[] = [
                'href' => $formatUrl,
                'title' => $format,
                'type' => $formatFactory->create($format)->getMimeType(),
            ];
        }

        if (Configuration::getConfig('admin', 'donations') && $extraInfos['donationUri'] !== '') {
            $buttons[] = [
                'href' => e($extraInfos['donationUri']),
                'value' => 'Donate to maintainer',
            ];
        }


        // Default behavior is to group by item
        $groupImagesBy = 'all'; // Possible values: 'item', 'all'

        // Check if the 'groupImages' parameter is set in the URL
        if (isset($_GET['groupImages'])) {
            $groupImagesBy = $_GET['groupImages'] === 'all' ? 'all' : 'item';
        }

        $items = [];
        $allGalleryItems = [];
        foreach ($this->getItems() as $item) {
            $galleryItems = [];

            $content = $item->getContent();

            $doc = new DOMDocument();
            @$doc->loadHTML($content); // The @ suppresses warnings generated by invalid HTML in the content.

            $tags = $doc->getElementsByTagName('img');

            foreach ($tags as $tag) {
                $imageSrc = $tag->getAttribute('src');
                $parent = $tag->parentNode;
                $linkHref = null;

                // Check if the img tag is wrapped in an a tag
                if ($parent instanceof DOMElement && $parent->tagName === 'a') {
                    $linkHref = $parent->getAttribute('href');
                }

                // Only add to the array if there is an image source
                if ($imageSrc) {
                    $galleryItems[] = [
                        'thumbnail' => $imageSrc,
                        'url' => $linkHref ?: $imageSrc, // Use the image source as a fallback if no link is present
                    ];
                }
            }
            //error_log("Title: " . $item->getTitle(), 3, "debug.log");
            if ($groupImagesBy === 'all') {
                // If grouping all images, collect them in a single array
                //error_log("Merging gallery items, count: " . count($galleryItems), 3, "debug.log");
                $allGalleryItems = array_merge($allGalleryItems, $galleryItems);
                //error_log("After merging, allGalleryItems count: " . count($allGalleryItems), 3, "debug.log");
            } else {
                $items[] = [
                    'url'           => $item->getURI() ?: $extraInfos['uri'],
                    'title'         => $item->getTitle() ?? '(no title)',
                    'timestamp'     => $item->getTimestamp(),
                    'author'        => $item->getAuthor(),
                    'content'       => $item->getContent() ?? '',
                    'enclosures'    => $item->getEnclosures(),
                    'categories'    => $item->getCategories(),
                    'galleryItems'  => $galleryItems,
                ];
            }
        }

        if ($groupImagesBy === 'all') {
            $items = [
                [
                    'galleryItems'  => $allGalleryItems,
                ]
            ];
        }

        $html = render_template(__DIR__ . '/../templates/justified-gallery-format.html.php', [
            'charset'   => $this->getCharset(),
            'title'     => $extraInfos['name'],
            'linkTags'  => $linkTags,
            'uri'       => $extraInfos['uri'],
            'buttons'   => $buttons,
            'items'     => $items,
        ]);
        // Remove invalid characters
        ini_set('mbstring.substitute_character', 'none');
        $html = mb_convert_encoding($html, $this->getCharset(), 'UTF-8');
        return $html;
    }
}
